version: '3.8'

services:
  apache-php:
    build: .
    container_name: osssd-cluster3
    ports:
      - "1303:80"
    volumes:
      - .:/var/www/html
    env_file:
      - .env
    volumes:
      - .:/var/www/html
    
